// Service worker: makes the site installable and fully usable offline.
// Strategy: precache every file at install; serve from cache, refresh in the background.
// @@PRECACHE-START (generated by scripts/gen_sw.py — do not edit)
const VERSION = '898fd89f7e7e';
const PRECACHE = [
  './',
  'index.html',
  'manifest.webmanifest',
  'css/fonts.css',
  'css/style.css',
  'js/app.js',
  'js/editor.js',
  'js/lib.js',
  'js/pixels.js',
  'js/registry.js',
  'js/scan-core.js',
  'js/tools/compress.js',
  'js/tools/crop.js',
  'js/tools/edit-text.js',
  'js/tools/fill.js',
  'js/tools/form.js',
  'js/tools/id-copy.js',
  'js/tools/image-compress.js',
  'js/tools/image.js',
  'js/tools/jpg-to-pdf.js',
  'js/tools/merge.js',
  'js/tools/organize.js',
  'js/tools/page-number.js',
  'js/tools/protect.js',
  'js/tools/redact.js',
  'js/tools/scan.js',
  'js/tools/sign.js',
  'js/tools/split.js',
  'js/tools/unlock.js',
  'js/tools/watermark.js',
  'js/work.js',
  'js/worker.js',
  'vendor/fonts/Charm-400-latin.woff2',
  'vendor/fonts/Charm-400-thai.woff2',
  'vendor/fonts/Charm-700-latin.woff2',
  'vendor/fonts/Charm-700-thai.woff2',
  'vendor/fonts/IBMPlexSansThai-400-latin.woff2',
  'vendor/fonts/IBMPlexSansThai-400-thai.woff2',
  'vendor/fonts/IBMPlexSansThai-500-latin.woff2',
  'vendor/fonts/IBMPlexSansThai-500-thai.woff2',
  'vendor/fonts/IBMPlexSansThai-600-latin.woff2',
  'vendor/fonts/IBMPlexSansThai-600-thai.woff2',
  'vendor/fonts/IBMPlexSansThai-700-latin.woff2',
  'vendor/fonts/IBMPlexSansThai-700-thai.woff2',
  'vendor/fonts/Itim-400-latin.woff2',
  'vendor/fonts/Itim-400-thai.woff2',
  'vendor/fonts/Kanit-500-latin.woff2',
  'vendor/fonts/Kanit-500-thai.woff2',
  'vendor/fonts/Kanit-600-latin.woff2',
  'vendor/fonts/Kanit-600-thai.woff2',
  'vendor/fonts/Kanit-700-latin.woff2',
  'vendor/fonts/Kanit-700-thai.woff2',
  'vendor/fonts/Mali-500-latin.woff2',
  'vendor/fonts/Mali-500-thai.woff2',
  'vendor/fonts/Sarabun-400-latin.woff2',
  'vendor/fonts/Sarabun-400-thai.woff2',
  'vendor/fonts/Sarabun-700-latin.woff2',
  'vendor/fonts/Sarabun-700-thai.woff2',
  'vendor/fonts/Srisakdi-700-latin.woff2',
  'vendor/fonts/Srisakdi-700-thai.woff2',
  'vendor/jsquash/codec/enc/mozjpeg_enc.js',
  'vendor/jsquash/codec/enc/mozjpeg_enc.wasm',
  'vendor/jsquash/codec/LICENSE.codec.md',
  'vendor/jsquash/encode.js',
  'vendor/jsquash/LICENSE',
  'vendor/jsquash/meta.js',
  'vendor/jsquash/utils.js',
  'vendor/jszip.min.js',
  'vendor/pako.min.js',
  'vendor/pdf-lib.min.js',
  'vendor/pdfjs/pdf.min.mjs',
  'vendor/pdfjs/pdf.worker.min.mjs',
  'vendor/Sortable.min.js',
  'icons/apple-touch-icon.png',
  'icons/icon-192.png',
  'icons/icon-512.png',
  'icons/icon-maskable-512.png',
];
// @@PRECACHE-END

const CACHE = 'pdftk-' + VERSION;

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(PRECACHE)));
});

self.addEventListener('activate', (e) => {
  e.waitUntil((async () => {
    for (const k of await caches.keys()) if (k !== CACHE) await caches.delete(k);
    await self.clients.claim();
  })());
});

// The page asks us to take over after the user accepts the "update available" prompt.
self.addEventListener('message', (e) => { if (e.data === 'skipWaiting') self.skipWaiting(); });

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== location.origin) return;
  e.respondWith((async () => {
    const cache = await caches.open(CACHE);
    // Query strings (?v=…) don't change the file; navigation requests all map to the app shell.
    const key = req.mode === 'navigate' ? './' : req;
    const hit = await cache.match(key, { ignoreSearch: true });
    const net = fetch(req).then(res => {
      if (res.ok && res.type === 'basic') cache.put(key, res.clone());
      return res;
    }).catch(() => null);
    if (hit) { e.waitUntil(net); return hit; }
    return (await net) || new Response('ออฟไลน์ — ไฟล์นี้ยังไม่ถูกเก็บไว้ในเครื่อง', { status: 503, headers: { 'Content-Type': 'text/plain; charset=utf-8' } });
  })());
});
