// Production build → dist/
//   npm run build        (then deploy the dist/ folder)
// Bundles + minifies the app JS (code-split per tool) and CSS, copies static assets,
// and regenerates the service-worker precache list for dist/.
import { build } from 'esbuild';
import { rmSync, mkdirSync, cpSync, readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dist = join(root, 'dist');
rmSync(dist, { recursive: true, force: true });
mkdirSync(dist, { recursive: true });

// JS: app + worker entry points; tools become separate chunks loaded on demand.
// Vendor files stay as-is (pdf.js / MozJPEG locate their own worker & wasm next to themselves).
await build({
  entryPoints: [join(root, 'js/app.js'), join(root, 'js/worker.js')],
  outdir: join(dist, 'js'),
  bundle: true, splitting: true, format: 'esm', minify: true,
  target: ['es2020', 'safari15'],
  chunkNames: '[name]-[hash]',
  external: ['../vendor/*'],
  legalComments: 'none',
  logLevel: 'warning',
});

await build({
  entryPoints: [join(root, 'css/style.css'), join(root, 'css/fonts.css')],
  outdir: join(dist, 'css'),
  minify: true, bundle: true,
  external: ['*.woff2'],
  logLevel: 'warning',
});

for (const p of ['vendor', 'icons', 'manifest.webmanifest', 'sw.js']) cpSync(join(root, p), join(dist, p), { recursive: true });

// index.html: drop the dev-only per-module preloads (modules are bundled now)
let html = readFileSync(join(root, 'index.html'), 'utf8');
html = html.replace(/^\s*<!-- Preload every tool module[^\n]*\n/m, '').replace(/^\s*<link rel="modulepreload"[^\n]*\n/gm, '');
writeFileSync(join(dist, 'index.html'), html);

// Service worker precache: every built file + a content hash as version (same format as scripts/gen_sw.py)
const walk = (d) => readdirSync(d).sort().flatMap(n => { const p = join(d, n); return statSync(p).isDirectory() ? walk(p) : [p]; });
const files = ['index.html', 'manifest.webmanifest', 'css', 'js', 'vendor', 'icons']
  .flatMap(e => { const p = join(dist, e); return statSync(p).isDirectory() ? walk(p) : [p]; });
const rel = (f) => relative(dist, f).split(/[\\/]/).join('/');
const hash = createHash('sha256');
for (const f of files) { hash.update(rel(f)); hash.update(readFileSync(f)); }
const version = hash.digest('hex').slice(0, 12);
const list = ['./', ...files.map(rel)].map(p => `  '${p}'`).join(',\n');
const swPath = join(dist, 'sw.js');
const sw = readFileSync(swPath, 'utf8');
const a = sw.indexOf('// @@PRECACHE-START'), b = sw.indexOf('// @@PRECACHE-END');
writeFileSync(swPath, sw.slice(0, a) +
  `// @@PRECACHE-START (generated by scripts/build.mjs)\nconst VERSION = '${version}';\nconst PRECACHE = [\n${list},\n];\n` +
  sw.slice(b));
const kb = (n) => (n / 1024).toFixed(0) + ' KB';
const size = (dir) => walk(join(dist, dir)).reduce((s, f) => s + statSync(f).size, 0);
console.log(`built → dist/  (js ${kb(size('js'))}, css ${kb(size('css'))}, sw version ${version}, ${files.length + 1} precached)`);
