"""Rebuild sw.js's precache list + version from the files on disk.

Run automatically by `npm run build` for dist/; for the unbuilt source run:  python scripts/gen_sw.py
The version is a hash of all file contents, so any change makes installed apps pick up the update.
"""
import hashlib
import sys
from pathlib import Path

# optional argument: the folder to scan (dist/ for production builds); default = project root
ROOT = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else Path(__file__).resolve().parent.parent
INCLUDE = ['index.html', 'manifest.webmanifest', 'css', 'js', 'vendor', 'icons']

files = []
for entry in INCLUDE:
    p = ROOT / entry
    files += [p] if p.is_file() else sorted(f for f in p.rglob('*') if f.is_file())

h = hashlib.sha256()
for f in files:
    h.update(f.relative_to(ROOT).as_posix().encode())
    h.update(f.read_bytes())
version = h.hexdigest()[:12]

paths = ['./'] + [f.relative_to(ROOT).as_posix() for f in files]
listing = ',\n'.join(f"  '{p}'" for p in paths)

sw = (ROOT / 'sw.js').read_text(encoding='utf-8')
start = sw.index('// @@PRECACHE-START')
end = sw.index('// @@PRECACHE-END')
block = f"// @@PRECACHE-START (generated by scripts/gen_sw.py — do not edit)\nconst VERSION = '{version}';\nconst PRECACHE = [\n{listing},\n];\n"
(ROOT / 'sw.js').write_text(sw[:start] + block + sw[end:], encoding='utf-8', newline='\n')
print(f'sw.js: version {version}, {len(paths)} files')
